### ISSUE TITLE
Add Webroot package to composer cache

### ISSUE THREAD

**Issue by dillongilmore** [fancyguy/webroot-installer#7]
Using the example on the readme.

```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "wordpress/wordpress",
                "type": "webroot",
                "version": "3.5.1",
                "source": {
                    "type": "git",
                    "url": "https://github.com/WordPress/WordPress.git",
                    "reference": "3.5.1"
                },
                "require": {
                    "fancyguy/webroot-installer": "1.0.0"
                }
            }
        }
    ],
    "require": {
        "wordpress/wordpress": "3.5.*"
    }
}
```

When using the above composer.json WordPress is successfully cloned in the correct locations and on subsequent updates it knows WordPress is on the same version so it doesn't clone. If the webroot directory is deleted and WordPress needs to be recloned it does a git clone on the repo. Ideally the webroot should be in composer's cache and loaded from there.

Let me know if I'm missing something or if that's really a missing feature!

**Comment by slbmeh** [comment]
As an installer it leverages composer's cache automatically. If you do a dist install it should cache the dist in `$COMPOSER_HOME/cache/files/{$package-name}/`. There is a limitation with VCS repositories in composer making it unable to clone from a cache. The repo cache is for repository metadata, and the vcs cache is a bare clone of the vcs repository.

More information on composer/composer#54, composer/composer#1323, and composer/composer#1338

**Comment by dillongilmore** [comment]
Cool, thanks for the information!
