### ISSUE TITLE
Post install scripts are not executed

### ISSUE THREAD

**Issue by mikemix** [fancyguy/webroot-installer#9]
After the first `composer install` the post install scripts are not fired.

> $ composer install
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> - Installing fancyguy/webroot-installer (1.0.0)
>   Loading from cache
> - Installing wordpress (4.5.1)
>   Loading from cache
> 
> Writing lock file
> Generating autoload files

I have to run `composer install` again to run scripts:

> $ composer install
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Nothing to install or update
> Generating autoload files
> [... scripts executing]

**Comment by sbuzonas** [comment]
An installer shouldn't have anything to do with the scripts block.  What does your composer.json look like?
